version: '2.1'
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.50.18.0/24
        gateway: 10.50.18.254

services:
#  mariadb-data:
#    image: busybox
#    container_name: "${DOMAIN_NAME}_mariadb-data"
#    volumes:
#      - "${DATA_PATH}/mariadb-data:/var/lib/mysql"

  froxlor-data:
    image: busybox
    container_name: "${DOMAIN_NAME}_froxlor-data"
    volumes:
      - "${DATA_PATH}/customers:/var/customers"
      - "${DATA_PATH}/mariadb-data:/var/lib/mysql"

  froxlor:
    environment:
       - HTTP_SERVER=${HTTP_SERVER}
       - "TZ=${TIMEZONE}"
    build:
      context: .
      dockerfile: froxlor/Dockerfile
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    hostname: ${DOMAIN_NAME}
    volumes_from:
      - froxlor-data
#      - mariadb-data
    container_name: "${DOMAIN_NAME}_froxlor"
    ports:
      -  "${HTTP_IP}:${HTTP_PORT}:80"
      -  "${HTTP_IP}:${HTTPS_PORT}:443"
      -  "${HTTP_IP}:${PORT_SFTP}:21"
    depends_on:
#      - mariadb-data
      - froxlor-data
    restart: always
    networks:
      app_net:
        ipv4_address: 10.50.18.1
#    logging:
#      driver: none


  bareos-fd:
    build:
      context: bareos-fd
      dockerfile: Dockerfile
    hostname: bareos-fd
    container_name: "${DOMAIN_NAME}_froxlor_bareos-fd"
    volumes_from:
      - froxlor-data
    volumes:
      - "${DATA_PATH}/client_bareos:/etc/bareos"
#    links:
#      - mysql:mysql
    ports:
      -  "${HTTP_IP}:${BAREOSFD_PORT}:9102"
    depends_on:
#      - mariadb-data
      - froxlor
    restart: always
    logging:
      driver: none


